#!/usr/bin/env ruby

require 'date'

def help_message
  puts "I'd cheer for you, if only I knew who you were :(\nTry again with ./cheers.rb [Name] [MM/DD Birthday]"
end

def cheer_message
  name = ARGV[0]
  name_gsub = name.gsub(/[\W\d]/, "")
  an_letters = "AEIOFLMNSRX"
  name_gsub.each_char do |c|
    if an_letters.include?(c.upcase)
      puts "Give me an.. #{c.upcase}"
    else
      puts "Give me a.. #{c.upcase}"
    end
  end
  puts "#{name}'s just GRAND!"
end

def birthday_message
  birthday = Date.parse(ARGV[1])
  today = Date.today
  diff = birthday - today
  days_until = diff.to_i % 365
  puts "Awesome! Your birthday is in #{days_until} days! Happy Birthday in advance!"
end

def valid_date
  maybe_date = ARGV[1]
  maybe_month = maybe_date[0..1].gsub(/[\D]/, "").to_i
  true if maybe_date.size < 7 && maybe_month <= 12 && maybe_month != 0
end

def valid_name
  maybe_name = ARGV[0]
  maybe_name_gsub = maybe_name.gsub(/[\W\d]/, "")
  if maybe_name_gsub.empty? || maybe_name.empty? || maybe_name.nil?
    false
  else
    true
  end
end

if ARGV.length == 1
  if valid_name
    cheer_message
  else
    help_message
  end
elsif ARGV.length == 2
  if valid_date
    cheer_message
    birthday_message
  else
    help_message
  end
else
  help_message
end
